version: "3.9"

services:
  smilecook-api:
    image: smilecook-api
    environment: # local credentials
      - MONGO_URI=mongodb://admin:password@mongodb:27017/test?authSource=admin&readPreference=primary&ssl=false
      - MONGO_DATABASE=demo
      - REDIS_URI=redis:6379
    networks:
      - smilecook_network
    external_links:
      - mongodb
      - redis
    depends_on:
      - redis
    scale: 5
  
  redis:
    image: redis
    networks:
      - smilecook_network
  
  mongodb:
    image: mongo:4.4.3
    networks:
      - smilecook_network
    environment: # local credentials
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - smilecook-api
    networks:
      - smilecook_network

networks:
  smilecook_network:
    external: true
