version: 2.1 # use CircleCI 2.1

executors:
  # run the workflows inside a golang docker image, this is done so as to make migrations easy and prevent vendor-lock-in
  # if we ever wish to change the CI provider in the future
  environment:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/skamranahmed/smilecook-api

jobs:
  test:
    executor: environment
    steps:
      - checkout # this instruction fetches the latest changes

      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - run:
          name: Install Dependencies
          command: go mod download

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - run:
          name: Unit tests
          command: go test -v ./...

  build:
    executor: environment
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true

      - run:
          name: Build Image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t skamranahmed/smilecook-api:$TAG --build-arg API_VERSION=${TAG} .

      - run:
          name: Push Image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker tag skamranahmed/smilecook-api:$TAG 034317561586.dkr.ecr.ap-south-1.amazonaws.com/smilecook:$TAG
            docker tag skamranahmed/smilecook-api:$TAG 034317561586.dkr.ecr.ap-south-1.amazonaws.com/smilecook:staging
            docker push 034317561586.dkr.ecr.ap-south-1.amazonaws.com/smilecook:$TAG
            docker push 034317561586.dkr.ecr.ap-south-1.amazonaws.com/smilecook:staging

workflows:
  ci_cd:
    jobs:
      - test
      - build
